println("Hello, welcome to the Kia Compiler")
println("Feel free to test some things out, but just a warning, this is still in extreme development")

println("Also sorry for any spelling errors in the comments (I'm not the best at spelling)")

println("To test it out run 'make start' to compile this file")
println("If you have a different file in this directory, just run 'python main.py [file_name]'")
println("For example, the code that make start runs is: 'python main.py test.k'")